FROM openjdk:17 as builder

WORKDIR /app

# Copy the packaged JAR file into the container at /app
COPY target/warehouse-0.0.1-SNAPSHOT.jar /app/warehouse.jar

# Expose the port that your Spring Boot application runs on (default is 8080)
EXPOSE 9090

# Specify the command to run your application when the container starts
CMD ["java", "-jar", "warehouse.jar"]