eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
server:
    port: 8761
spring:
    application:
        name: eureka-service
    boot:
        admin:
            client:
                url: http://localhost:9889
management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
        info:
            enabled: true
