eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
    server:
        enableSelfPreservation: false
server:
    port: 8761
spring:
    application:
        name: eureka-service
#    boot:
#        admin:
#            client:
#                url: http://172.27.176.1:9889
management:
    endpoints:
        web:
            base-path: /actuator-${spring.application.name}
            exposure:
                include: '*'
            endpoint:
                health:
                    show-details: always
                info:
                    enabled: true
                env:
                    enabled: true
    endpoint:
        health:
            show-details: always
        info:
            enabled: true

