#eureka:
#    client:
#        fetch-registry: false
#        register-with-eureka: false
#server:
#    port: 8761
spring:
    application:
        name: eureka-service
    config:
        import: optional:configserver:http://localhost:9797
