spring:
  application:
    name: stock-service
  config:
    import: optional:configserver:http://config-server:9797


#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#        jdbc:
#          time_zone: UTC
#  datasource:
#    url: jdbc:mysql://localhost:3306/stock
#    username: admin
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#
#kafka:
#  host: localhost:9092
#  topics:
#    waybill-record:
#      topic: warehouse-service.waybill-record.0
#      consumerGroup: ${spring.application.name}-waybill-record-consumer
#      replicationFactor: 1
#      retentionInMs: 604800000
#
#eureka:
#  client:
#    service-url:
#      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    instance-id: '${spring.application.name}:${random.value}  '
#    prefer-ip-address: true
#server:
#  port: 0
