spring:
  application:
    name: stock-service
couchbase:
  stock-service:
    config:
      bootstrapHosts: localhost
      stockBucket: stock
      stockBucketUsername: admin
      stockBucketPassword: 123456
kafka:
  host: localhost:9092
  topics:
    waybill-record:
      topic: warehouse.waybill-record.0
      consumerGroup: ${spring.application.name}-waybill-record-consumer
server:
  port: 5050
