spring:
  application:
    name: stock-service

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:mysql://localhost:3306/stock
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver


kafka:
  host: localhost:9092
  topics:
    waybill-record:
      topic: warehouse-service.waybill-record.0
      consumerGroup: ${spring.application.name}-waybill-record-consumer
      replicationFactor: 1
      retentionInMs: 604800000
server:
  port: 9393
