spring:
  application:
    name: finance-service
  config:
    import: optional:configserver:http://localhost:9797
#  profiles:
#    active: default
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#  datasource:
#    url: jdbc:postgresql://localhost:5432/finance
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#
#
#kafka:
#  host: localhost:9092
#  topics:
#    waybill-invoice:
#      topic: warehouse-service.waybill-invoice.0
#      consumerGroup: ${spring.application.name}-waybill-invoice-consumer
#      replicationFactor: 1
#      retentionInMs: 604800000
#
#
#eureka:
#  client:
#    service-url:
#      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    instance-id: '${spring.application.name}:${random.value}  '
#    prefer-ip-address: true
#server:
#  port: 0
