spring:
  application:
    name: finance-service

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


kafka:
  host: localhost:9092
  topics:
    waybill-invoice:
      topic: warehouse-service.waybill-invoice.0
      consumerGroup: ${spring.application.name}-waybill-invoice-consumer
      replicationFactor: 1
      retentionInMs: 604800000
server:
  port: 9494
